In [46]:
import pandas as pd
import pickle

with open('./total_df.pickle', 'rb') as f:
    data = pickle.load(f)


data

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN,play_type,made_shot,event_pts_val,shot_val,secs_remaining_in_qtr,total_secs_remaining,season
0,0022301188,8,2,5,1,1:12 PM,11:38,None,None,MISS Fernando 3' Layup,0 - 0,0,LAYUP,0,2,0,698,2858,2023-24
1,0022301188,11,2,1,1,1:12 PM,11:28,MISS Haliburton 24' 3PT Jump Shot,None,None,0 - 0,0,3PT_JUMP_SHOT,0,3,0,688,2848,2023-24
2,0022301188,15,2,63,1,1:13 PM,11:13,None,None,MISS Hunter 11' Fadeaway Jumper,0 - 0,0,FADEAWAY_JUMPER,0,2,0,673,2833,2023-24
3,0022301188,17,1,98,1,1:13 PM,11:02,Turner 4' Cutting Layup Shot (2 PTS) (Haliburt...,None,None,0 - 2,2,CUTTING_LAYUP_SHOT,1,2,2,662,2822,2023-24
4,0022301188,22,2,5,1,1:14 PM,10:50,None,None,MISS Fernando 6' Layup,0 - 2,2,LAYUP,0,2,0,650,2810,2023-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,0021800666,646,2,79,4,9:19 PM,0:50,MISS Bridges 25' 3PT Pullup Jump Shot,None,None,93 - 109,16,3PT_PULLUP_JUMP_SHOT,0,3,0,50,50,2018-19
171,0021800666,650,2,1,4,9:19 PM,0:37,None,None,MISS McLemore 26' 3PT Jump Shot,93 - 109,16,3PT_JUMP_SHOT,0,3,0,37,37,2018-19
172,0021800666,652,1,1,4,9:19 PM,0:28,Monk 26' 3PT Jump Shot (5 PTS) (Bridges 1 AST),None,None,93 - 114,21,3PT_JUMP_SHOT,1,3,3,28,28,2018-19
173,0021800666,654,2,5,4,9:20 PM,0:07,None,None,MISS McLemore 2' Layup,93 - 114,21,LAYUP,0,2,0,7,7,2018-19
174,0021800666,656,1,97,4,9:20 PM,0:06,None,None,Bagley 1' III 1' Tip Layup Shot (15 PTS),95 - 114,19,III_1,1,2,2,6,6,2018-19

In [47]:
import re
def extract_distance(description):
    # Find all matches of distances in the format of a number followed by a single quote
    matches = re.findall(r'(\d+)\'' , description)
    
    if matches:
        # Return the second value if there are multiple matches (e.g., error case)
        if len(matches) > 1:
            return matches[1]  # Take the second value in case of an error
        return matches[0]
    return None

data['Distance'] = data.apply(lambda row: extract_distance(row['HOMEDESCRIPTION']) 
                                         if pd.notna(row['HOMEDESCRIPTION']) 
                                         else extract_distance(row['VISITORDESCRIPTION']), axis=1)

data['Distance'] = data['Distance'].str.replace("'", "", regex=False).astype(int)

data

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN,play_type,made_shot,event_pts_val,shot_val,secs_remaining_in_qtr,total_secs_remaining,season,Distance
0,0022301188,8,2,5,1,1:12 PM,11:38,None,None,MISS Fernando 3' Layup,0 - 0,0,LAYUP,0,2,0,698,2858,2023-24,3
1,0022301188,11,2,1,1,1:12 PM,11:28,MISS Haliburton 24' 3PT Jump Shot,None,None,0 - 0,0,3PT_JUMP_SHOT,0,3,0,688,2848,2023-24,24
2,0022301188,15,2,63,1,1:13 PM,11:13,None,None,MISS Hunter 11' Fadeaway Jumper,0 - 0,0,FADEAWAY_JUMPER,0,2,0,673,2833,2023-24,11
3,0022301188,17,1,98,1,1:13 PM,11:02,Turner 4' Cutting Layup Shot (2 PTS) (Haliburt...,None,None,0 - 2,2,CUTTING_LAYUP_SHOT,1,2,2,662,2822,2023-24,4
4,0022301188,22,2,5,1,1:14 PM,10:50,None,None,MISS Fernando 6' Layup,0 - 2,2,LAYUP,0,2,0,650,2810,2023-24,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,0021800666,646,2,79,4,9:19 PM,0:50,MISS Bridges 25' 3PT Pullup Jump Shot,None,None,93 - 109,16,3PT_PULLUP_JUMP_SHOT,0,3,0,50,50,2018-19,25
171,0021800666,650,2,1,4,9:19 PM,0:37,None,None,MISS McLemore 26' 3PT Jump Shot,93 - 109,16,3PT_JUMP_SHOT,0,3,0,37,37,2018-19,26
172,0021800666,652,1,1,4,9:19 PM,0:28,Monk 26' 3PT Jump Shot (5 PTS) (Bridges 1 AST),None,None,93 - 114,21,3PT_JUMP_SHOT,1,3,3,28,28,2018-19,26
173,0021800666,654,2,5,4,9:20 PM,0:07,None,None,MISS McLemore 2' Layup,93 - 114,21,LAYUP,0,2,0,7,7,2018-19,2
174,0021800666,656,1,97,4,9:20 PM,0:06,None,None,Bagley 1' III 1' Tip Layup Shot (15 PTS),95 - 114,19,III_1,1,2,2,6,6,2018-19,1

In [48]:
data.loc[data['play_type'] == 'JACKSON_2']

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN,play_type,made_shot,event_pts_val,shot_val,secs_remaining_in_qtr,total_secs_remaining,season,Distance
167,0022301188,596,2,73,4,3:07 PM,6:11,MISS Q. 1' Jackson 2' Driving Reverse Layup,None,None,108 - 144,36,JACKSON_2,0,2,0,371,371,2023-24,2
44,0022100176,167,2,9,2,8:11 PM,11:09,None,None,MISS J. 1' Jackson 2' Driving Dunk,18 - 26,8,JACKSON_2,0,2,0,669,2109,2021-22,2
155,0022100176,600,1,41,4,9:36 PM,1:30,None,None,F. 1' Jackson 2' Running Layup (11 PTS),74 - 95,21,JACKSON_2,1,2,2,90,90,2021-22,2
15,0022100004,41,1,6,1,7:18 PM,8:35,F. 1' Jackson 2' Driving Layup (2 PTS),None,None,4 - 6,2,JACKSON_2,1,2,2,515,2675,2021-22,2
47,0022100004,142,1,75,1,7:34 PM,1:30,J. 1' Jackson 2' Driving Finger Roll Layup (2 ...,None,None,14 - 18,4,JACKSON_2,1,2,2,90,2250,2021-22,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,0022000957,346,2,73,2,8:09 PM,0:20,None,None,MISS F. 1' Jackson 2' Driving Reverse Layup,42 - 57,15,JACKSON_2,0,2,0,20,1460,2020-21,2
146,0022000957,545,1,6,4,8:54 PM,10:33,None,None,J. 1' Jackson 2' Driving Layup (5 PTS) (Lee 7 ...,75 - 83,8,JACKSON_2,1,2,2,633,633,2020-21,2
151,0022000957,569,2,108,4,8:59 PM,9:04,None,None,MISS F. 1' Jackson 2' Cutting Dunk Shot,80 - 83,3,JACKSON_2,0,2,0,544,544,2020-21,2
51,0022000568,168,2,5,2,7:38 PM,11:03,None,None,MISS J. 1' Jackson 2' Layup,22 - 30,8,JACKSON_2,0,2,0,663,2103,2020-21,2
122,0022000568,447,1,75,3,8:34 PM,2:49,None,None,J. 1' Jackson 2' Driving Finger Roll Layup (4 ...,67 - 66,-1,JACKSON_2,1,2,2,169,889,2020-21,2

In [49]:
overtime_data = data.loc[data['PERIOD'] > 4]
regular_data = data.loc[data['PERIOD'] <= 4]

overtime_data['total_secs_remaining'] = overtime_data['secs_remaining_in_qtr']

data = pd.concat([regular_data, overtime_data])

event_play_type_mapping = data.groupby('EVENTMSGACTIONTYPE')['play_type'].unique().reset_index()

event_play_type_mapping['first_play_type'] = event_play_type_mapping['play_type'].apply(lambda x: x[0])

mapping_dict = event_play_type_mapping.set_index('EVENTMSGACTIONTYPE')['first_play_type'].to_dict()

data

/tmp/ipykernel_2364185/3420808785.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  overtime_data['total_secs_remaining'] = overtime_data['secs_remaining_in_qtr']

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN,play_type,made_shot,event_pts_val,shot_val,secs_remaining_in_qtr,total_secs_remaining,season,Distance
0,0022301188,8,2,5,1,1:12 PM,11:38,None,None,MISS Fernando 3' Layup,0 - 0,0,LAYUP,0,2,0,698,2858,2023-24,3
1,0022301188,11,2,1,1,1:12 PM,11:28,MISS Haliburton 24' 3PT Jump Shot,None,None,0 - 0,0,3PT_JUMP_SHOT,0,3,0,688,2848,2023-24,24
2,0022301188,15,2,63,1,1:13 PM,11:13,None,None,MISS Hunter 11' Fadeaway Jumper,0 - 0,0,FADEAWAY_JUMPER,0,2,0,673,2833,2023-24,11
3,0022301188,17,1,98,1,1:13 PM,11:02,Turner 4' Cutting Layup Shot (2 PTS) (Haliburt...,None,None,0 - 2,2,CUTTING_LAYUP_SHOT,1,2,2,662,2822,2023-24,4
4,0022301188,22,2,5,1,1:14 PM,10:50,None,None,MISS Fernando 6' Layup,0 - 2,2,LAYUP,0,2,0,650,2810,2023-24,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,0021800046,777,1,1,5,12:38 AM,0:38,None,None,Morris 25' 3PT Jump Shot (28 PTS) (Wall 9 AST),123 - 119,-4,3PT_JUMP_SHOT,1,3,3,38,38,2018-19,25
214,0021800046,780,1,79,5,12:39 AM,0:32,Lillard 21' Pullup Jump Shot (29 PTS),None,None,123 - 121,-2,PULLUP_JUMP_SHOT,1,2,2,32,32,2018-19,21
215,0021800046,781,1,79,5,12:40 AM,0:10,None,None,Wall 17' Pullup Jump Shot (16 PTS),125 - 121,-4,PULLUP_JUMP_SHOT,1,2,2,10,10,2018-19,17
216,0021800046,785,1,47,5,12:41 AM,0:07,McCollum 1' 3PT Turnaround Jump Shot (13 PTS) ...,None,None,125 - 124,-1,3PT_TURNAROUND_JUMP_SHOT,1,3,3,7,7,2018-19,1
217,0021800046,795,2,41,5,12:43 AM,0:00,MISS Lillard 2' Running Layup,None,None,125 - 124,-1,RUNNING_LAYUP,0,2,0,0,0,2018-19,2

In [50]:
data = data.drop(['EVENTNUM', 'EVENTMSGTYPE', 'WCTIMESTRING', 'PCTIMESTRING', 'HOMEDESCRIPTION', 'NEUTRALDESCRIPTION', 'VISITORDESCRIPTION', 'SCORE', 'play_type'], axis=1)

data['SCOREMARGIN'] = data['SCOREMARGIN'].replace('TIE', 0)
data['SCOREMARGIN'] = data['SCOREMARGIN'].astype(int).abs()
data

,GAME_ID,EVENTMSGACTIONTYPE,PERIOD,SCOREMARGIN,made_shot,event_pts_val,shot_val,secs_remaining_in_qtr,total_secs_remaining,season,Distance
0,0022301188,5,1,0,0,2,0,698,2858,2023-24,3
1,0022301188,1,1,0,0,3,0,688,2848,2023-24,24
2,0022301188,63,1,0,0,2,0,673,2833,2023-24,11
3,0022301188,98,1,2,1,2,2,662,2822,2023-24,4
4,0022301188,5,1,2,0,2,0,650,2810,2023-24,6
...,...,...,...,...,...,...,...,...,...,...,...
213,0021800046,1,5,4,1,3,3,38,38,2018-19,25
214,0021800046,79,5,2,1,2,2,32,32,2018-19,21
215,0021800046,79,5,4,1,2,2,10,10,2018-19,17
216,0021800046,47,5,1,1,3,3,7,7,2018-19,1
217,0021800046,41,5,1,0,2,0,0,0,2018-19,2

In [51]:
train_data = data.loc[~(data['season'] == '2023-24')]
train_data = train_data.drop(['season', 'shot_val', 'GAME_ID'], axis=1)

train_data['SCOREMARGIN'].unique()

array([ 0,  1,  2,  3,  5,  4,  7,  6, 10,  8, 11,  9, 12, 13, 15, 14, 16,
       18, 21, 19, 17, 20, 22, 23, 24, 26, 25, 27, 29, 28, 31, 32, 30, 35,
       37, 33, 34, 36, 38, 41, 43, 40, 39, 44, 42, 46, 49, 48, 45, 47, 50,
       51, 53, 56, 59, 57, 55, 58, 60, 54, 52, 62, 64, 66, 68, 70, 72, 74,
       76, 78, 75, 73, 61, 63, 65, 67])

In [52]:
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier

X = train_data.drop(columns=['made_shot'])
y = train_data['made_shot']

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the CatBoost Classifier
model = CatBoostClassifier(verbose=0)
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

In [53]:
y_pred = model.predict_proba(X_test)

X_test['prob_make'] = y_pred[:, 1]

In [54]:
X_test

,EVENTMSGACTIONTYPE,PERIOD,SCOREMARGIN,event_pts_val,secs_remaining_in_qtr,total_secs_remaining,Distance,prob_make
52,78,2,12,2,606,2046,10,0.431471
105,6,3,9,2,416,1136,7,0.257737
79,78,2,2,2,177,1617,15,0.440609
168,79,4,3,3,299,299,27,0.340205
170,78,4,3,2,110,110,9,0.453413
...,...,...,...,...,...,...,...,...
76,102,2,1,2,227,1667,7,0.506410
66,79,2,5,3,426,1866,25,0.352958
46,6,2,12,2,529,1969,5,0.284036
139,1,3,3,3,90,810,25,0.346336
95,52,2,11,2,95,1535,2,0.867601

In [55]:
with open('./this_season_data.pickle', 'rb') as f:
    test_data = pickle.load(f)

test_data['Distance'] = test_data.apply(lambda row: extract_distance(row['HOMEDESCRIPTION']) 
                                         if pd.notna(row['HOMEDESCRIPTION']) 
                                         else extract_distance(row['VISITORDESCRIPTION']), axis=1)

test_data['Distance'] = test_data['Distance'].str.replace("'", "", regex=False).astype(int)

overtime_data = test_data.loc[test_data['PERIOD'] > 4]
regular_data = test_data.loc[test_data['PERIOD'] <= 4]

overtime_data['total_secs_remaining'] = overtime_data['secs_remaining_in_qtr']

test_data = pd.concat([regular_data, overtime_data])

/tmp/ipykernel_2364185/1104864117.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  overtime_data['total_secs_remaining'] = overtime_data['secs_remaining_in_qtr']

In [56]:
def split_matchup(row):
    if '@' in row:  # Format is 'Away @ Home'
        away, home = row.split(' @ ')
    elif 'vs' in row:  # Format is 'Home vs Away'
        home, away = row.split(' vs. ')
    return pd.Series([home, away])

test_data[['Home_Team', 'Away_Team']] = test_data['matchup'].apply(split_matchup)

def get_defending_team(row):
    if row['PLAYER1_TEAM_ABBREVIATION'] == row['Home_Team']:
        return row['Away_Team']  # Offensive team is Home, so defending team is Away
    else:
        return row['Home_Team']  # Offensive team is Away, so defending team is Home

# Create the 'Defending_Team_Abbreviation' column
test_data['Defending_Team'] = test_data.apply(get_defending_team, axis=1)



test_data

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,...,event_pts_val,shot_val,secs_remaining_in_qtr,total_secs_remaining,season,matchup,Distance,Home_Team,Away_Team,Defending_Team
0,0022301188,8,2,5,1,1:12 PM,11:38,None,None,MISS Fernando 3' Layup,...,2,0,698,2858,2023-24,ATL @ IND,3,IND,ATL,IND
1,0022301188,11,2,1,1,1:12 PM,11:28,MISS Haliburton 24' 3PT Jump Shot,None,None,...,3,0,688,2848,2023-24,ATL @ IND,24,IND,ATL,ATL
2,0022301188,15,2,63,1,1:13 PM,11:13,None,None,MISS Hunter 11' Fadeaway Jumper,...,2,0,673,2833,2023-24,ATL @ IND,11,IND,ATL,IND
3,0022301188,17,1,98,1,1:13 PM,11:02,Turner 4' Cutting Layup Shot (2 PTS) (Haliburt...,None,None,...,2,2,662,2822,2023-24,ATL @ IND,4,IND,ATL,ATL
4,0022301188,22,2,5,1,1:14 PM,10:50,None,None,MISS Fernando 6' Layup,...,2,0,650,2810,2023-24,ATL @ IND,6,IND,ATL,IND
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,0022300474,716,2,1,5,11:41 PM,1:11,None,None,MISS Cunningham 24' 3PT Jump Shot,...,3,0,71,71,2023-24,UTA vs. DET,24,UTA,DET,UTA
204,0022300474,722,2,80,5,11:43 PM,0:45,MISS Fontecchio 14' Step Back Jump Shot,None,None,...,2,0,45,45,2023-24,UTA vs. DET,14,UTA,DET,DET
205,0022300474,724,2,5,5,11:43 PM,0:31,None,None,MISS Burks 3' Layup,...,2,0,31,31,2023-24,UTA vs. DET,3,UTA,DET,UTA
206,0022300474,751,1,1,5,11:49 PM,0:07,None,None,Cunningham 25' 3PT Jump Shot (31 PTS) (Ivey 2 ...,...,3,3,7,7,2023-24,UTA vs. DET,25,UTA,DET,UTA
207,0022300474,768,2,79,5,11:54 PM,0:00,None,None,MISS Ivey 27' 3PT Pullup Jump Shot,...,3,0,0,0,2023-24,UTA vs. DET,27,UTA,DET,UTA

In [57]:
team_defense_rankings = pd.read_csv('team_defense_rankings.csv')

team_defense_rankings = team_defense_rankings.sort_values('2FG%', ascending=True).reset_index(drop=True).reset_index().rename(columns={'index': '2FG_rank'})

team_defense_rankings = team_defense_rankings.sort_values('3P%', ascending=True).reset_index(drop=True).reset_index().rename(columns={'index': '3FG_rank'})

team_defense_rankings['2FG_rank'] = team_defense_rankings['2FG_rank'] + 1
team_defense_rankings['3FG_rank'] = team_defense_rankings['3FG_rank'] + 1
team_defense_rankings = team_defense_rankings[['TEAM', '2FG_rank', '3FG_rank']]

team_defense_rankings

   TEAM  2FG_rank  3FG_rank
0   NOP        22         1
1   HOU        10         2
2   POR        30         3
3   BOS         2         4
4   MIA        20         5
5   MIN         1         6
6   DEN         4         7
7   PHI        15         8
8   MIL        14         9
9   GSW        12        10
10  ORL        17        11
11  OKC         3        12
12  WAS        28        13
13  LAC         8        14
14  NYK         9        15
15  IND        25        16
16  PHX         6        17
17  DET        24        18
18  DAL        18        19
19  CHI        23        20
20  CLE         5        21
21  BKN         7        22
22  SAS        21        23
23  TOR        26        24
24  LAL        16        25
25  CHA        29        26
26  MEM        13        27
27  ATL        27        28
28  SAC        11        29
29  UTA        19        30

0        Atlanta Hawks
1       Indiana Pacers
2        Atlanta Hawks
3       Indiana Pacers
4        Atlanta Hawks
            ...
203    Detroit Pistons
204          Utah Jazz
205    Detroit Pistons
206    Detroit Pistons
207    Detroit Pistons
Length: 218705, dtype: object

In [59]:
shot_vals = test_data['shot_val']
player_info = test_data[['PLAYER1_NAME', 'PLAYER1_ID']]
game_ids = test_data['GAME_ID']
defending_team = test_data['Defending_Team']
offense_team = test_data['PLAYER1_TEAM_CITY'] + " " + test_data['PLAYER1_TEAM_NICKNAME']
test_data = test_data.drop(['season', 'shot_val', 'GAME_ID', 'EVENTNUM', 'EVENTMSGTYPE',
       'WCTIMESTRING', 'PCTIMESTRING', 'HOMEDESCRIPTION', 'NEUTRALDESCRIPTION',
       'VISITORDESCRIPTION', 'SCORE', 'PERSON1TYPE',
       'PLAYER1_ID', 'PLAYER1_NAME', 'PLAYER1_TEAM_ID', 'PLAYER1_TEAM_CITY',
       'PLAYER1_TEAM_NICKNAME', 'PLAYER1_TEAM_ABBREVIATION', 'PERSON2TYPE',
       'PLAYER2_ID', 'PLAYER2_NAME', 'PLAYER2_TEAM_ID', 'PLAYER2_TEAM_CITY',
       'PLAYER2_TEAM_NICKNAME', 'PLAYER2_TEAM_ABBREVIATION', 'PERSON3TYPE',
       'PLAYER3_ID', 'PLAYER3_NAME', 'PLAYER3_TEAM_ID', 'PLAYER3_TEAM_CITY',
       'PLAYER3_TEAM_NICKNAME', 'PLAYER3_TEAM_ABBREVIATION',
       'VIDEO_AVAILABLE_FLAG', 'play_type', 'matchup', 'Home_Team', 'Away_Team', 'Defending_Team'], axis=1)

In [60]:
test_data['SCOREMARGIN'] = test_data['SCOREMARGIN'].replace('TIE', 0)
test_data['SCOREMARGIN'] = test_data['SCOREMARGIN'].astype(int).abs()

y_pred = model.predict_proba(test_data)
test_data['prob_make'] = y_pred[:, 1]
test_data['shot_val'] = shot_vals
test_data['GAME_ID'] = game_ids
test_data['defending_team'] = defending_team
test_data['offense_team'] = offense_team

In [61]:
test_data = pd.concat([test_data, player_info], axis=1)

test_data['expected_pts'] = test_data['event_pts_val'] * test_data['prob_make']

test_data['pts_vs_expected'] = test_data['shot_val'] - test_data['expected_pts']

test_data

,EVENTMSGACTIONTYPE,PERIOD,SCOREMARGIN,made_shot,event_pts_val,secs_remaining_in_qtr,total_secs_remaining,Distance,prob_make,shot_val,GAME_ID,defending_team,offense_team,PLAYER1_NAME,PLAYER1_ID,expected_pts,pts_vs_expected
0,5,1,0,0,2,698,2858,3,0.353963,0,0022301188,IND,Atlanta Hawks,Bruno Fernando,1628981,0.707925,-0.707925
1,1,1,0,0,3,688,2848,24,0.166349,0,0022301188,ATL,Indiana Pacers,Tyrese Haliburton,1630169,0.499047,-0.499047
2,63,1,0,0,2,673,2833,11,0.217513,0,0022301188,IND,Atlanta Hawks,De'Andre Hunter,1629631,0.435026,-0.435026
3,98,1,2,1,2,662,2822,4,0.674667,2,0022301188,ATL,Indiana Pacers,Myles Turner,1626167,1.349334,0.650666
4,5,1,2,0,2,650,2810,6,0.319790,0,0022301188,IND,Atlanta Hawks,Bruno Fernando,1628981,0.639579,-0.639579
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,1,5,7,0,3,71,71,24,0.304951,0,0022300474,UTA,Detroit Pistons,Cade Cunningham,1630595,0.914854,-0.914854
204,80,5,7,0,2,45,45,14,0.402448,0,0022300474,DET,Utah Jazz,Simone Fontecchio,1631323,0.804896,-0.804896
205,5,5,7,0,2,31,31,3,0.378375,0,0022300474,UTA,Detroit Pistons,Alec Burks,202692,0.756751,-0.756751
206,1,5,3,1,3,7,7,25,0.211279,3,0022300474,UTA,Detroit Pistons,Cade Cunningham,1630595,0.633837,2.366163
207,79,5,3,0,3,0,0,27,0.123294,0,0022300474,UTA,Detroit Pistons,Jaden Ivey,1631093,0.369881,-0.369881

In [62]:
test_data['play_type'] = test_data['EVENTMSGACTIONTYPE'].map(mapping_dict)


test_data

,EVENTMSGACTIONTYPE,PERIOD,SCOREMARGIN,made_shot,event_pts_val,secs_remaining_in_qtr,total_secs_remaining,Distance,prob_make,shot_val,GAME_ID,defending_team,offense_team,PLAYER1_NAME,PLAYER1_ID,expected_pts,pts_vs_expected,play_type
0,5,1,0,0,2,698,2858,3,0.353963,0,0022301188,IND,Atlanta Hawks,Bruno Fernando,1628981,0.707925,-0.707925,LAYUP
1,1,1,0,0,3,688,2848,24,0.166349,0,0022301188,ATL,Indiana Pacers,Tyrese Haliburton,1630169,0.499047,-0.499047,3PT_JUMP_SHOT
2,63,1,0,0,2,673,2833,11,0.217513,0,0022301188,IND,Atlanta Hawks,De'Andre Hunter,1629631,0.435026,-0.435026,FADEAWAY_JUMPER
3,98,1,2,1,2,662,2822,4,0.674667,2,0022301188,ATL,Indiana Pacers,Myles Turner,1626167,1.349334,0.650666,CUTTING_LAYUP_SHOT
4,5,1,2,0,2,650,2810,6,0.319790,0,0022301188,IND,Atlanta Hawks,Bruno Fernando,1628981,0.639579,-0.639579,LAYUP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,1,5,7,0,3,71,71,24,0.304951,0,0022300474,UTA,Detroit Pistons,Cade Cunningham,1630595,0.914854,-0.914854,3PT_JUMP_SHOT
204,80,5,7,0,2,45,45,14,0.402448,0,0022300474,DET,Utah Jazz,Simone Fontecchio,1631323,0.804896,-0.804896,3PT_STEP_BACK_JUMP_SHOT
205,5,5,7,0,2,31,31,3,0.378375,0,0022300474,UTA,Detroit Pistons,Alec Burks,202692,0.756751,-0.756751,LAYUP
206,1,5,3,1,3,7,7,25,0.211279,3,0022300474,UTA,Detroit Pistons,Cade Cunningham,1630595,0.633837,2.366163,3PT_JUMP_SHOT
207,79,5,3,0,3,0,0,27,0.123294,0,0022300474,UTA,Detroit Pistons,Jaden Ivey,1631093,0.369881,-0.369881,PULLUP_JUMP_SHOT

In [63]:
test_data = pd.merge(test_data, team_defense_rankings, left_on='defending_team', right_on='TEAM', how='left')

def assign_defending_rank(row):
    if '3PT' in row['play_type']:
        return row['3FG_rank']  # Assign 3FG rank for 3PT plays
    else:
        return row['2FG_rank']  # Assign 2FG rank for other plays

# Create the 'defending_team_rk' column
test_data['defending_team_rk'] = test_data.apply(assign_defending_rank, axis=1)

test_data = test_data.drop(['TEAM', '2FG_rank', '3FG_rank'], axis=1)

test_data

,EVENTMSGACTIONTYPE,PERIOD,SCOREMARGIN,made_shot,event_pts_val,secs_remaining_in_qtr,total_secs_remaining,Distance,prob_make,shot_val,GAME_ID,defending_team,offense_team,PLAYER1_NAME,PLAYER1_ID,expected_pts,pts_vs_expected,play_type,defending_team_rk
0,5,1,0,0,2,698,2858,3,0.353963,0,0022301188,IND,Atlanta Hawks,Bruno Fernando,1628981,0.707925,-0.707925,LAYUP,25
1,1,1,0,0,3,688,2848,24,0.166349,0,0022301188,ATL,Indiana Pacers,Tyrese Haliburton,1630169,0.499047,-0.499047,3PT_JUMP_SHOT,28
2,63,1,0,0,2,673,2833,11,0.217513,0,0022301188,IND,Atlanta Hawks,De'Andre Hunter,1629631,0.435026,-0.435026,FADEAWAY_JUMPER,25
3,98,1,2,1,2,662,2822,4,0.674667,2,0022301188,ATL,Indiana Pacers,Myles Turner,1626167,1.349334,0.650666,CUTTING_LAYUP_SHOT,27
4,5,1,2,0,2,650,2810,6,0.319790,0,0022301188,IND,Atlanta Hawks,Bruno Fernando,1628981,0.639579,-0.639579,LAYUP,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218700,1,5,7,0,3,71,71,24,0.304951,0,0022300474,UTA,Detroit Pistons,Cade Cunningham,1630595,0.914854,-0.914854,3PT_JUMP_SHOT,30
218701,80,5,7,0,2,45,45,14,0.402448,0,0022300474,DET,Utah Jazz,Simone Fontecchio,1631323,0.804896,-0.804896,3PT_STEP_BACK_JUMP_SHOT,18
218702,5,5,7,0,2,31,31,3,0.378375,0,0022300474,UTA,Detroit Pistons,Alec Burks,202692,0.756751,-0.756751,LAYUP,19
218703,1,5,3,1,3,7,7,25,0.211279,3,0022300474,UTA,Detroit Pistons,Cade Cunningham,1630595,0.633837,2.366163,3PT_JUMP_SHOT,30
218704,79,5,3,0,3,0,0,27,0.123294,0,0022300474,UTA,Detroit Pistons,Jaden Ivey,1631093,0.369881,-0.369881,PULLUP_JUMP_SHOT,19

In [64]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0, 1))
test_data['normalized_seconds_remaining'] = 1 - scaler.fit_transform(test_data[['total_secs_remaining']])  # Reversed so later time is weighted more

# Normalize 'scoremargin' (close games get higher weight)
test_data['normalized_scoremargin'] = 1 - scaler.fit_transform(test_data[['SCOREMARGIN']].abs())  # Closer games have higher weight

# Normalize 'period' (later periods, especially overtime, are more important)
test_data['normalized_defending_tm'] = 1 - scaler.fit_transform(test_data[['defending_team_rk']])

# Create a final contextual weight by combining all normalized factors
# This is a simple example of multiplying the three normalized weights
test_data['cpoe'] = (test_data['normalized_seconds_remaining'] * 0.4 +
                           test_data['normalized_scoremargin'] * 0.4 + 
                           test_data['normalized_defending_tm'] * 0.2)  * test_data['pts_vs_expected']

test_data

,EVENTMSGACTIONTYPE,PERIOD,SCOREMARGIN,made_shot,event_pts_val,secs_remaining_in_qtr,total_secs_remaining,Distance,prob_make,shot_val,...,PLAYER1_NAME,PLAYER1_ID,expected_pts,pts_vs_expected,play_type,defending_team_rk,normalized_seconds_remaining,normalized_scoremargin,normalized_defending_tm,cpoe
0,5,1,0,0,2,698,2858,3,0.353963,0,...,Bruno Fernando,1628981,0.707925,-0.707925,LAYUP,25,0.006604,1.000000,0.172414,-0.309451
1,1,1,0,0,3,688,2848,24,0.166349,0,...,Tyrese Haliburton,1630169,0.499047,-0.499047,3PT_JUMP_SHOT,28,0.010080,1.000000,0.068966,-0.208515
2,63,1,0,0,2,673,2833,11,0.217513,0,...,De'Andre Hunter,1629631,0.435026,-0.435026,FADEAWAY_JUMPER,25,0.015294,1.000000,0.172414,-0.191673
3,98,1,2,1,2,662,2822,4,0.674667,2,...,Myles Turner,1626167,1.349334,0.650666,CUTTING_LAYUP_SHOT,27,0.019117,0.967742,0.103448,0.270308
4,5,1,2,0,2,650,2810,6,0.319790,0,...,Bruno Fernando,1628981,0.639579,-0.639579,LAYUP,25,0.023288,0.967742,0.172414,-0.275591
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218700,1,5,7,0,3,71,71,24,0.304951,0,...,Cade Cunningham,1630595,0.914854,-0.914854,3PT_JUMP_SHOT,30,0.975322,0.887097,0.000000,-0.681537
218701,80,5,7,0,2,45,45,14,0.402448,0,...,Simone Fontecchio,1631323,0.804896,-0.804896,3PT_STEP_BACK_JUMP_SHOT,18,0.984359,0.887097,0.413793,-0.669143
218702,5,5,7,0,2,31,31,3,0.378375,0,...,Alec Burks,202692,0.756751,-0.756751,LAYUP,19,0.989225,0.887097,0.379310,-0.625372
218703,1,5,3,1,3,7,7,25,0.211279,3,...,Cade Cunningham,1630595,0.633837,2.366163,3PT_JUMP_SHOT,30,0.997567,0.951613,0.000000,1.844831
218704,79,5,3,0,3,0,0,27,0.123294,0,...,Jaden Ivey,1631093,0.369881,-0.369881,PULLUP_JUMP_SHOT,19,1.000000,0.951613,0.379310,-0.316806

In [65]:
test_data.sort_values('cpoe', ascending=False)

,EVENTMSGACTIONTYPE,PERIOD,SCOREMARGIN,made_shot,event_pts_val,secs_remaining_in_qtr,total_secs_remaining,Distance,prob_make,shot_val,...,PLAYER1_NAME,PLAYER1_ID,expected_pts,pts_vs_expected,play_type,defending_team_rk,normalized_seconds_remaining,normalized_scoremargin,normalized_defending_tm,cpoe
104537,1,4,1,1,3,1,1,34,0.091367,3,...,Taylor Hendricks,1641707,0.274100,2.725900,3PT_JUMP_SHOT,2,0.999652,0.983871,0.965517,2.689135
217810,79,5,5,1,3,4,4,36,0.071210,3,...,Fred VanVleet,1627832,0.213631,2.786369,PULLUP_JUMP_SHOT,5,0.998610,0.919355,0.862069,2.618071
218506,1,6,0,1,3,276,276,28,0.009334,3,...,Jordan Clarkson,203903,0.028001,2.971999,3PT_JUMP_SHOT,17,0.904067,1.000000,0.448276,2.530009
87111,79,4,3,1,3,0,0,39,0.068601,3,...,Nikola Jokic,203999,0.205803,2.794197,PULLUP_JUMP_SHOT,12,1.000000,0.951613,0.620690,2.528142
32989,79,4,2,1,3,0,0,59,0.042252,3,...,Max Strus,1629622,0.126756,2.873244,PULLUP_JUMP_SHOT,18,1.000000,0.967742,0.413793,2.499307
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27974,103,4,0,0,3,39,39,26,0.597529,0,...,Anthony Edwards,1630162,1.792588,-1.792588,3PT_RUNNING_PULL,4,0.986444,1.000000,0.896552,-1.745780
2094,7,4,3,0,2,117,117,1,0.917916,0,...,Clint Capela,203991,1.835832,-1.835832,DUNK,2,0.959333,0.951613,0.965517,-1.757776
114962,109,4,0,0,2,210,210,2,0.957527,0,...,Jalen Suggs,1630591,1.915054,-1.915054,DRIVING_REVERSE_DUNK_SHOT,8,0.927007,1.000000,0.758621,-1.766689
218088,1,5,3,0,3,274,274,26,0.694394,0,...,Klay Thompson,202691,2.083181,-2.083181,3PT_JUMP_SHOT,12,0.904762,0.951613,0.620690,-1.805467
26587,7,4,4,0,2,34,34,1,0.946058,0,...,Mark Williams,1631109,1.892116,-1.892116,DUNK,2,0.988182,0.935484,0.965517,-1.821294

In [66]:
test_data.to_csv('cpoe_results.csv')

In [39]:
pd.DataFrame(test_data.groupby(['PLAYER1_ID', 'PLAYER1_NAME'])['cpoe'].sum()).reset_index().sort_values('cpoe', ascending=False).head(20)

     PLAYER1_ID             PLAYER1_NAME        cpoe
97       203999             Nikola Jokic  199.185941
4        201142             Kevin Durant  140.458067
20       201939            Stephen Curry  119.362456
222     1629029              Luka Doncic  110.948707
194     1628983  Shai Gilgeous-Alexander  100.407691
33       202681             Kyrie Irving   99.235048
0          2544             LeBron James   96.807421
31       202331              Paul George   93.709561
188     1628973            Jalen Brunson   93.185406
115     1626181            Norman Powell   88.971432
41       202695            Kawhi Leonard   87.037587
449     1631114           Jalen Williams   76.921279
149     1628368             De'Aaron Fox   76.473003
90       203954              Joel Embiid   69.622689
100      204456           T.J. McConnell   68.090168
246     1629627          Zion Williamson   67.646860
107     1626164             Devin Booker   67.266314
179     1628960            Grayson Allen   67.192750
123     1627734         Domantas Sabonis   66.832385
380     1630559            Austin Reaves   64.485880

In [40]:
pd.DataFrame(test_data.groupby(['PLAYER1_ID', 'PLAYER1_NAME'])['cpoe'].sum()).reset_index().sort_values('cpoe', ascending=False).tail(20)

     PLAYER1_ID       PLAYER1_NAME       cpoe
510     1641708      Amen Thompson -35.027535
476     1631212      Peyton Watson -35.314976
83       203932       Aaron Gordon -35.326356
332     1630224        Jalen Green -35.691390
300     1630173   Precious Achiuwa -39.390126
360     1630533    Ziaire Williams -39.520232
470     1631200        Kris Murray -39.898305
168     1628404          Josh Hart -42.577104
273     1629673       Jordan Poole -44.953152
305     1630180         Saddiq Bey -45.437448
484     1631223        David Roddy -46.464505
361     1630534       Ochai Agbaji -47.917210
420     1630692     Jordan Goodwin -48.057054
93       203991       Clint Capela -50.681538
10       201566  Russell Westbrook -55.087706
507     1641705  Victor Wembanyama -56.210325
129     1627747       Caris LeVert -59.377867
106     1626162    Kelly Oubre Jr. -60.545543
446     1631110      Jeremy Sochan -69.839219
426     1630703    Scoot Henderson -74.646407

In [42]:
pd.DataFrame(test_data.groupby(['PLAYER1_ID', 'PLAYER1_NAME', 'play_type'])['cpoe'].sum()).reset_index().sort_values('cpoe', ascending=False).head(20)

       PLAYER1_ID        PLAYER1_NAME      play_type       cpoe
522        201939       Stephen Curry  3PT_JUMP_SHOT  78.914597
758        202331         Paul George  3PT_JUMP_SHOT  72.693063
3131      1626181       Norman Powell  3PT_JUMP_SHOT  64.002454
97         201142        Kevin Durant  3PT_JUMP_SHOT  61.390903
6115      1629029         Luka Doncic  DRIVING_LAYUP  50.121633
2366       203954         Joel Embiid  3PT_JUMP_SHOT  49.646391
4297      1628379        Luke Kennard  3PT_JUMP_SHOT  47.936468
6600      1629627     Zion Williamson  DRIVING_LAYUP  47.309061
7355      1629675            Naz Reid  3PT_JUMP_SHOT  47.190272
4221      1628374     Lauri Markkanen  3PT_JUMP_SHOT  47.169265
15           2544        LeBron James  DRIVING_LAYUP  46.225861
4912      1628960       Grayson Allen  3PT_JUMP_SHOT  45.827628
8446      1630198          Isaiah Joe  3PT_JUMP_SHOT  42.454873
5695      1629008  Michael Porter Jr.  3PT_JUMP_SHOT  40.877481
4071      1628368        De'Aaron Fox  DRIVING_LAYUP  40.311848
817        202681        Kyrie Irving  3PT_JUMP_SHOT  40.256686
2778      1626157  Karl-Anthony Towns  3PT_JUMP_SHOT  39.557308
4615      1628401       Derrick White  3PT_JUMP_SHOT  37.933782
10005     1630573          Sam Hauser  3PT_JUMP_SHOT  37.172116
2747      1626156    D'Angelo Russell  3PT_JUMP_SHOT  35.944401

In [43]:
pd.DataFrame(test_data.groupby(['PLAYER1_ID', 'PLAYER1_NAME', 'play_type'])['cpoe'].sum()).reset_index().sort_values('cpoe', ascending=False).tail(20)

       PLAYER1_ID       PLAYER1_NAME                play_type       cpoe
3916      1627832      Fred VanVleet  3PT_STEP_BACK_JUMP_SHOT -18.882479
10782     1630703    Scoot Henderson            DRIVING_LAYUP -18.981038
2070       203915  Spencer Dinwiddie         PULLUP_JUMP_SHOT -19.167071
3726      1627763    Malcolm Brogdon         PULLUP_JUMP_SHOT -19.205448
1063       202696     Nikola Vucevic            3PT_JUMP_SHOT -19.364753
7641      1630162    Anthony Edwards         PULLUP_JUMP_SHOT -19.674240
9352      1630534       Ochai Agbaji            3PT_JUMP_SHOT -20.304260
12550     1641708      Amen Thompson            3PT_JUMP_SHOT -20.489018
12062     1631223        David Roddy            3PT_JUMP_SHOT -20.722616
7303      1629673       Jordan Poole  3PT_STEP_BACK_JUMP_SHOT -20.748979
12439     1641705  Victor Wembanyama            3PT_JUMP_SHOT -20.863674
5971      1629023    P.J. Washington            3PT_JUMP_SHOT -21.344164
274        201566  Russell Westbrook            3PT_JUMP_SHOT -22.168129
4316      1628380       Zach Collins            3PT_JUMP_SHOT -22.835886
11822     1631200        Kris Murray            3PT_JUMP_SHOT -23.159617
9280      1630532       Franz Wagner            3PT_JUMP_SHOT -23.726777
4284      1628378   Donovan Mitchell         PULLUP_JUMP_SHOT -24.673413
9829      1630560         Cam Thomas  3PT_STEP_BACK_JUMP_SHOT -25.725583
8101      1630178       Tyrese Maxey         PULLUP_JUMP_SHOT -26.317513
12586     1641709     Ausar Thompson            3PT_JUMP_SHOT -33.174479

In [44]:
pd.DataFrame(test_data.groupby('play_type')['cpoe'].mean()).reset_index().sort_values('cpoe', ascending=False)

                             play_type      cpoe
39            STEP_BACK_BANK_JUMP_SHOT  0.106348
0                   3PT_JUMP_BANK_SHOT  0.081282
26                               LAYUP  0.068703
45  TURNAROUND_FADEAWAY_BANK_JUMP_SHOT  0.059135
16                       DRIVING_LAYUP  0.056762
31                       REVERSE_LAYUP  0.050633
19                                DUNK  0.043914
37           RUNNING_REVERSE_DUNK_SHOT  0.041102
18               DRIVING_REVERSE_LAYUP  0.031675
1                        3PT_JUMP_SHOT  0.028650
22                   FINGER_ROLL_LAYUP  0.027179
40                       TIP_DUNK_SHOT  0.026148
6                      ALLEY_OOP_LAYUP  0.025592
9                   CUTTING_LAYUP_SHOT  0.023552
5                       ALLEY_OOP_DUNK  0.023336
32         RUNNING_ALLEY_OOP_DUNK_SHOT  0.022567
23                  FLOATING_JUMP_SHOT  0.018047
12           DRIVING_FINGER_ROLL_LAYUP  0.017253
11                        DRIVING_DUNK  0.016063
28                        PUTBACK_DUNK  0.013750
34                        RUNNING_DUNK  0.005664
35           RUNNING_FINGER_ROLL_LAYUP  0.005423
7                    CUTTING_DUNK_SHOT  0.000723
14          DRIVING_FLOATING_JUMP_SHOT -0.000612
46                TURNAROUND_HOOK_SHOT -0.000820
25                           HOOK_SHOT -0.002747
44                 TURNAROUND_FADEAWAY -0.005357
30                        REVERSE_DUNK -0.006724
27                    PULLUP_JUMP_SHOT -0.008723
41                      TIP_LAYUP_SHOT -0.009090
21                     FADEAWAY_JUMPER -0.011876
47                TURNAROUND_JUMP_SHOT -0.012724
36                       RUNNING_LAYUP -0.013478
29                       PUTBACK_LAYUP -0.013495
8       CUTTING_FINGER_ROLL_LAYUP_SHOT -0.015487
4              3PT_STEP_BACK_JUMP_SHOT -0.017278
42           TURNAROUND_BANK_HOOK_SHOT -0.021791
13     DRIVING_FLOATING_BANK_JUMP_SHOT -0.022358
15                   DRIVING_HOOK_SHOT -0.024845
43                TURNAROUND_BANK_SHOT -0.026238
38               RUNNING_REVERSE_LAYUP -0.028267
24                      HOOK_BANK_SHOT -0.032457
20                  FADEAWAY_BANK_SHOT -0.044281
3                     3PT_RUNNING_PULL -0.054605
2                3PT_RUNNING_JUMP_SHOT -0.057950
10              DRIVING_BANK_HOOK_SHOT -0.079771
17           DRIVING_REVERSE_DUNK_SHOT -0.117601
33        RUNNING_ALLEY_OOP_LAYUP_SHOT -0.135614

In [17]:
pd.DataFrame(test_data.groupby('play_type')['pts_vs_expected'].mean()).reset_index().sort_values('pts_vs_expected', ascending=False)

                             play_type  pts_vs_expected
39            STEP_BACK_BANK_JUMP_SHOT         0.190097
0                   3PT_JUMP_BANK_SHOT         0.138765
45  TURNAROUND_FADEAWAY_BANK_JUMP_SHOT         0.113808
26                               LAYUP         0.110414
16                       DRIVING_LAYUP         0.089388
31                       REVERSE_LAYUP         0.085561
19                                DUNK         0.075471
18               DRIVING_REVERSE_LAYUP         0.052122
1                        3PT_JUMP_SHOT         0.048275
37           RUNNING_REVERSE_DUNK_SHOT         0.046675
6                      ALLEY_OOP_LAYUP         0.043311
22                   FINGER_ROLL_LAYUP         0.042156
40                       TIP_DUNK_SHOT         0.040827
9                   CUTTING_LAYUP_SHOT         0.039629
5                       ALLEY_OOP_DUNK         0.033329
11                        DRIVING_DUNK         0.031751
32         RUNNING_ALLEY_OOP_DUNK_SHOT         0.030225
23                  FLOATING_JUMP_SHOT         0.027669
12           DRIVING_FINGER_ROLL_LAYUP         0.026916
28                        PUTBACK_DUNK         0.026643
34                        RUNNING_DUNK         0.011470
35           RUNNING_FINGER_ROLL_LAYUP         0.002300
46                TURNAROUND_HOOK_SHOT         0.001586
14          DRIVING_FLOATING_JUMP_SHOT         0.001275
7                    CUTTING_DUNK_SHOT         0.001001
25                           HOOK_SHOT         0.000115
44                 TURNAROUND_FADEAWAY        -0.009015
36                       RUNNING_LAYUP        -0.013170
27                    PULLUP_JUMP_SHOT        -0.014079
29                       PUTBACK_LAYUP        -0.014336
41                      TIP_LAYUP_SHOT        -0.014763
24                      HOOK_BANK_SHOT        -0.016542
47                TURNAROUND_JUMP_SHOT        -0.016654
21                     FADEAWAY_JUMPER        -0.019044
30                        REVERSE_DUNK        -0.021234
4              3PT_STEP_BACK_JUMP_SHOT        -0.024344
8       CUTTING_FINGER_ROLL_LAYUP_SHOT        -0.026583
42           TURNAROUND_BANK_HOOK_SHOT        -0.035915
15                   DRIVING_HOOK_SHOT        -0.036385
13     DRIVING_FLOATING_BANK_JUMP_SHOT        -0.037009
38               RUNNING_REVERSE_LAYUP        -0.037934
43                TURNAROUND_BANK_SHOT        -0.046124
3                     3PT_RUNNING_PULL        -0.084468
20                  FADEAWAY_BANK_SHOT        -0.084775
2                3PT_RUNNING_JUMP_SHOT        -0.085980
10              DRIVING_BANK_HOOK_SHOT        -0.127014
17           DRIVING_REVERSE_DUNK_SHOT        -0.163818
33        RUNNING_ALLEY_OOP_LAYUP_SHOT        -0.210693

In [18]:
pd.DataFrame(test_data.groupby('play_type')['prob_make'].mean()).reset_index().sort_values('prob_make', ascending=False)

                             play_type  prob_make
37           RUNNING_REVERSE_DUNK_SHOT   0.947251
34                        RUNNING_DUNK   0.929183
30                        REVERSE_DUNK   0.916129
7                    CUTTING_DUNK_SHOT   0.913984
32         RUNNING_ALLEY_OOP_DUNK_SHOT   0.898401
28                        PUTBACK_DUNK   0.885464
17           DRIVING_REVERSE_DUNK_SHOT   0.876781
5                       ALLEY_OOP_DUNK   0.874143
40                       TIP_DUNK_SHOT   0.851320
19                                DUNK   0.839844
8       CUTTING_FINGER_ROLL_LAYUP_SHOT   0.800525
11                        DRIVING_DUNK   0.790883
35           RUNNING_FINGER_ROLL_LAYUP   0.744144
33        RUNNING_ALLEY_OOP_LAYUP_SHOT   0.737779
38               RUNNING_REVERSE_LAYUP   0.681758
9                   CUTTING_LAYUP_SHOT   0.674732
29                       PUTBACK_LAYUP   0.660181
31                       REVERSE_LAYUP   0.630005
12           DRIVING_FINGER_ROLL_LAYUP   0.618806
22                   FINGER_ROLL_LAYUP   0.618308
43                TURNAROUND_BANK_SHOT   0.616118
6                      ALLEY_OOP_LAYUP   0.609235
36                       RUNNING_LAYUP   0.597690
42           TURNAROUND_BANK_HOOK_SHOT   0.587402
10              DRIVING_BANK_HOOK_SHOT   0.574983
24                      HOOK_BANK_SHOT   0.563827
20                  FADEAWAY_BANK_SHOT   0.554317
18               DRIVING_REVERSE_LAYUP   0.553470
13     DRIVING_FLOATING_BANK_JUMP_SHOT   0.526046
45  TURNAROUND_FADEAWAY_BANK_JUMP_SHOT   0.512355
39            STEP_BACK_BANK_JUMP_SHOT   0.504841
0                   3PT_JUMP_BANK_SHOT   0.499393
41                      TIP_LAYUP_SHOT   0.492030
46                TURNAROUND_HOOK_SHOT   0.490853
25                           HOOK_SHOT   0.463345
26                               LAYUP   0.451556
15                   DRIVING_HOOK_SHOT   0.447934
16                       DRIVING_LAYUP   0.443015
23                  FLOATING_JUMP_SHOT   0.438747
44                 TURNAROUND_FADEAWAY   0.434022
14          DRIVING_FLOATING_JUMP_SHOT   0.428663
2                3PT_RUNNING_JUMP_SHOT   0.426817
3                     3PT_RUNNING_PULL   0.425134
47                TURNAROUND_JUMP_SHOT   0.409639
21                     FADEAWAY_JUMPER   0.400169
27                    PULLUP_JUMP_SHOT   0.398905
4              3PT_STEP_BACK_JUMP_SHOT   0.389130
1                        3PT_JUMP_SHOT   0.358547

In [63]:
pd.concat([test_data, player_info], axis=1)

,EVENTMSGACTIONTYPE,PERIOD,SCOREMARGIN,made_shot,event_pts_val,secs_remaining_in_qtr,total_secs_remaining,Distance,prob_make,shot_val,GAME_ID,PLAYER1_NAME,PLAYER1_ID
0,5,1,0,0,2,698,2858,3,0.353963,0,0022301188,Bruno Fernando,1628981
1,1,1,0,0,3,688,2848,24,0.166349,0,0022301188,Tyrese Haliburton,1630169
2,63,1,0,0,2,673,2833,11,0.217513,0,0022301188,De'Andre Hunter,1629631
3,98,1,2,1,2,662,2822,4,0.674667,2,0022301188,Myles Turner,1626167
4,5,1,2,0,2,650,2810,6,0.319790,0,0022301188,Bruno Fernando,1628981
...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,1,5,7,0,3,71,71,24,0.304951,0,0022300474,Cade Cunningham,1630595
204,80,5,7,0,2,45,45,14,0.402448,0,0022300474,Simone Fontecchio,1631323
205,5,5,7,0,2,31,31,3,0.378375,0,0022300474,Alec Burks,202692
206,1,5,3,1,3,7,7,25,0.211279,3,0022300474,Cade Cunningham,1630595
207,79,5,3,0,3,0,0,27,0.123294,0,0022300474,Jaden Ivey,1631093

In [64]:
test_data

,EVENTMSGACTIONTYPE,PERIOD,SCOREMARGIN,made_shot,event_pts_val,secs_remaining_in_qtr,total_secs_remaining,Distance,prob_make,shot_val,GAME_ID
0,5,1,0,0,2,698,2858,3,0.353963,0,0022301188
1,1,1,0,0,3,688,2848,24,0.166349,0,0022301188
2,63,1,0,0,2,673,2833,11,0.217513,0,0022301188
3,98,1,2,1,2,662,2822,4,0.674667,2,0022301188
4,5,1,2,0,2,650,2810,6,0.319790,0,0022301188
...,...,...,...,...,...,...,...,...,...,...,...
203,1,5,7,0,3,71,71,24,0.304951,0,0022300474
204,80,5,7,0,2,45,45,14,0.402448,0,0022300474
205,5,5,7,0,2,31,31,3,0.378375,0,0022300474
206,1,5,3,1,3,7,7,25,0.211279,3,0022300474
207,79,5,3,0,3,0,0,27,0.123294,0,0022300474

Index(['EVENTMSGACTIONTYPE', 'PERIOD', 'SCOREMARGIN', 'made_shot',
       'event_pts_val', 'secs_remaining_in_qtr_x', 'total_secs_remaining_x',
       'Distance', 'prob_make', 'shot_val', 'GAME_ID', 'expected_pts',
       'pts_vs_expected', 'play_type_x', 'normalized_seconds_remaining',
       'normalized_scoremargin', 'cpoe', 'EVENTNUM', 'EVENTMSGTYPE',
       'WCTIMESTRING', 'PCTIMESTRING', 'HOMEDESCRIPTION', 'NEUTRALDESCRIPTION',
       'VISITORDESCRIPTION', 'SCORE', 'PERSON1TYPE', 'PLAYER1_ID',
       'PLAYER1_NAME', 'PLAYER1_TEAM_ID', 'PLAYER1_TEAM_CITY',
       'PLAYER1_TEAM_NICKNAME', 'PLAYER1_TEAM_ABBREVIATION', 'PERSON2TYPE',
       'PLAYER2_ID', 'PLAYER2_NAME', 'PLAYER2_TEAM_ID', 'PLAYER2_TEAM_CITY',
       'PLAYER2_TEAM_NICKNAME', 'PLAYER2_TEAM_ABBREVIATION', 'PERSON3TYPE',
       'PLAYER3_ID', 'PLAYER3_NAME', 'PLAYER3_TEAM_ID', 'PLAYER3_TEAM_CITY',
       'PLAYER3_TEAM_NICKNAME', 'PLAYER3_TEAM_ABBREVIATION',
       'VIDEO_AVAILABLE_FLAG', 'play_type_y', 'secs_remaining_in_qtr_y',
       'total_secs_remaining_y', 'season', 'matchup'],
      dtype='object')

In [34]:
trial

,EVENTMSGACTIONTYPE,PERIOD,SCOREMARGIN,made_shot,event_pts_val,secs_remaining_in_qtr_x,total_secs_remaining_x,Distance,prob_make,shot_val,...,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG,play_type_y,secs_remaining_in_qtr_y,total_secs_remaining_y,season,matchup
0,5,1,0,0,2,698,2858,3,0.353963,0,...,1.610613e+09,Indiana,Pacers,IND,1,LAYUP,698,2858,2023-24,ATL @ IND
1,1,1,0,0,3,688,2848,24,0.166349,0,...,NaN,None,None,None,1,3PT_JUMP_SHOT,688,2848,2023-24,ATL @ IND
2,63,1,0,0,2,673,2833,11,0.217513,0,...,NaN,None,None,None,1,FADEAWAY_JUMPER,673,2833,2023-24,ATL @ IND
3,80,1,0,0,3,683,2843,24,0.139300,0,...,NaN,None,None,None,1,3PT_STEP_BACK_JUMP_SHOT,683,2843,2023-24,ATL @ MIN
4,47,1,0,0,2,672,2832,12,0.215302,0,...,NaN,None,None,None,1,TURNAROUND_JUMP_SHOT,672,2832,2023-24,ATL @ MIN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3729,1,1,0,0,3,697,2857,28,0.221655,0,...,NaN,None,None,None,1,3PT_JUMP_SHOT,697,2857,2023-24,DET vs. CHA
3730,1,1,0,0,3,602,2762,24,0.272310,0,...,NaN,None,None,None,1,3PT_JUMP_SHOT,697,2857,2023-24,DET vs. CHA
3731,101,1,0,0,2,700,2860,16,0.323997,0,...,NaN,None,None,None,1,DRIVING_FLOATING_JUMP_SHOT,700,2860,2023-24,DET vs. CHA
3732,6,1,0,0,2,699,2859,2,0.447713,0,...,1.610613e+09,Detroit,Pistons,DET,1,DRIVING_LAYUP,699,2859,2023-24,DET @ CHA
3733,101,1,0,0,2,679,2839,2,0.170375,0,...,NaN,None,None,None,1,DRIVING_FLOATING_JUMP_SHOT,679,2839,2023-24,DET @ CHA